service: ${file(./package.json):name}
provider:
  name: aws
  runtime: rust
  memorySize: 128
  region: eu-central-1

custom:
  rust:
    dockerless: true

package:
  individually: true

plugins:
  - serverless-rust

functions:
  hello:
    handler: ./target/release/hello
  world:
    handler: ./target/release/world